### ISSUE TITLE
complete network session scripts

### ISSUE THREAD

**Issue by pearsonca** [cmmid/MTM-2023#3]
Re all of these items: should be done in `inst/scripts/solutions/networks`, so that they can be processed per #2

- [x] review warmup after refactoring in #1 and #2 (@sophiemeakin)
- [x] review basicSIR after refactoring in #1 and #2
- [x] review altSIR after refactoring in #1 and #2
- [x] review netSIR after refactoring in #1 and #2

**Comment by pearsonca** [comment]
closed by #5
